import os, sys, commands

Import('env')
Import('platform_libs')

env = env.Clone()

prgs = []

prgs += env.Program('thread_id', ['thread_id.cc'], LIBS = platform_libs)
prgs += env.Program('yield', ['yield.cc'], LIBS = platform_libs)
prgs += env.Program('sleep_for', ['sleep_for.cc'], LIBS = platform_libs)

Return('prgs')
