Import('env')
Import('jsoncpp_include_path')

env = env.Clone()

objs = []
objs += env.Object('os_exec_op', ['os_exec_op.cc'])
objs += env.Object('log', ['log.cc'])
objs += env.Object('daemon_op', ['daemon_op.cc'])
objs += env.Object('chunk_head_op', ['chunk_head_op.cc'])
objs += env.Object('buffer', ['buffer.cc'])
objs += env.Object('filepath_op', ['filepath_op.cc'])
objs += env.Object('wait_event', ['wait_event.cc'])
objs += env.Object('this_thread_op', ['this_thread_op.cc'])
objs += env.Object('task_thread', ['task_thread.cc'])
objs += env.Object('redis_backend', ['redis_backend.cc'])
objs += env.Object('thread_pool', ['thread_pool.cc'])
objs += env.Object('stuff', ['stuff.cc'])

objs += env.Object('json_config', ['json_config.cc'], CPPPATH = jsoncpp_include_path)

Return('objs')
