Import('env')
Import('jsoncpp_include_path')
Import('libcurl_include_path')

env = env.Clone()

objs = []
objs += env.Object('os_exec_op', ['os_exec_op.cc'])
objs += env.Object('log', ['log.cc'])
objs += env.Object('daemon_op', ['daemon_op.cc'])
objs += env.Object('chunk_head_op', ['chunk_head_op.cc'])
objs += env.Object('buffer', ['buffer.cc'])
objs += env.Object('filepath_op', ['filepath_op.cc'])
objs += env.Object('wait_event', ['chef_wait_event.cc'])
objs += env.Object('this_thread_op', ['this_thread_op.cc'])
objs += env.Object('task_thread', ['chef_task_thread.cc'])
objs += env.Object('redis_backend', ['redis_backend.cc'])
objs += env.Object('thread_pool', ['thread_pool.cc'])
objs += env.Object('stuff', ['stuff.cc'])
objs += env.Object('count_dump', ['count_dump.cc'])
objs += env.Object('strings_op', ['strings_op.cc'])
objs += env.Object('this_proc_op', ['this_proc_op.cc'])
objs += env.Object('this_machine_op', ['this_machine_op.cc'])
objs += env.Object('logo', ['logo.cc'])
objs += env.Object('wait_event_counter', ['chef_wait_event_counter.cc'])

# objs += env.Object('crypto_md5_op', ['crypto_md5_op.cc'])
# objs += env.Object('encoding_base64_op', ['encoding_base64_op.cc'])

objs += env.Object('json_config', ['json_config.cc'], CPPPATH=jsoncpp_include_path)
objs += env.Object('http_op', ['http_op.cc'], CPPPATH=libcurl_include_path)

Return('objs')
